// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99zfqOkPJWhND2ECMfiLaP5AC_Ah6-qg',
    appId: '1:638132787336:web:32f7b36a7b53003dd3273d',
    messagingSenderId: '638132787336',
    projectId: 'projeto-flutter-1df97',
    authDomain: 'projeto-flutter-1df97.firebaseapp.com',
    storageBucket: 'projeto-flutter-1df97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBspSmpHwU6UJxzyXCRQJB4wv607YeOesI',
    appId: '1:638132787336:android:fbe3dfae8bd1e440d3273d',
    messagingSenderId: '638132787336',
    projectId: 'projeto-flutter-1df97',
    storageBucket: 'projeto-flutter-1df97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoEhILNqWyljpFSlXbQ8vrbYouUkNMVqg',
    appId: '1:638132787336:ios:c42cc27d0e8a73a1d3273d',
    messagingSenderId: '638132787336',
    projectId: 'projeto-flutter-1df97',
    storageBucket: 'projeto-flutter-1df97.appspot.com',
    iosBundleId: 'com.example.projetoFlutter2',
  );
}
